---
- hosts: localhost
  connection: local
  vars:
    ssh_port: 3232
  tasks:
    - name: Install vim
      yum:
        state: present
        name: vim
        update_cache: yes
      become: true

    - name: Install pip
      yum:
        state: present
        name: python-pip
      become: true

    - name: Install epel
      yum:
        state: present
        name: epel-release
      become: true

    - name: Install osquery RPM
      yum:
        state: present
        name: https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
      become: true

    - name: Install osquery
      yum:
        state: present
        name: osquery
      become: true

    - name: Install git
      yum:
        state: present
        name: git
      become: true
      
    - name: Update SSH Config
      template:
        src: /etc/ansible/Ansible_Learning/Templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
        notify:
        - Restart SSH
     
  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted 
